### ISSUE TITLE
[core] Error re-running playbook with repository installation method

### ISSUE THREAD

**Issue by acch** [IBM/ibm-spectrum-scale-install-infra#191]
Ansible Version: 2.9.10 (Fedora 32)
Scale Version: 5.0.4.1 (RHEL 7.8 x86_64)
*dev* branch

***

I have a `playbook.yml` along the lines of:

```
- hosts: ...
  vars:
    - scale_install_repository_url: ...
    - scale_install_gplbin_rpm: ...
    - scale_install_gplbin_repository_url: ...
    - scale_cluster_clustername: ...
  roles:
    - base  # <-- my own
    - core/precheck
    - core/node
    - core/cluster
    - core/postcheck
```

Running this playbook once on a freshly provisioned set of VMs works fine. It creates the cluster and filesystem according to my configuration (verified using `mmlscluster`, `mmgetstate`, `mmlsfs` and `mmlsmount`).

However, running the exact same playbooks again, without changing the configuration in any way, fails with the following error:

```
The task includes an option with an undefined variable.
The error was: 'gpfs_path_url' is undefined

The error appears to be in '.../ibm-spectrum-scale-install-infra/roles/core/node/tasks/upgrade.yml': line 18, column 3, but may be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

- name: update | Find available version
  ^ here
```

According to the principle of [idempotence](https://en.wikipedia.org/wiki/Idempotence), this error is unexpected.
