### ISSUE TITLE
Install gplsrc prereqs on Centos

### ISSUE THREAD

**Issue by olemyk** [IBM/ibm-spectrum-scale-install-infra#193]
When installing against Centos, the task " build | Install prereqs for building GPL from source"  is only checking RedHat os and not Centos. 

An easy fix is just adding  _RedHat OR Centos._
Or use Ansible_ value that cover both Centos And RedHat

And why are we using block for this task?

```
    - block:  ## when: rhel8 node
        - name: build | Install prereqs for building GPL from source
          dnf:
            name: "{{ scale_build_gplsrc_el8_prereqs }}"
            state: present
      when: ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS' and ansible_distribution_major_version == '8'
```
