### ISSUE TITLE
Support for updating repository url if repo file is already exist

### ISSUE THREAD

**Issue by rajan-mis** [IBM/ibm-spectrum-scale-install-infra#273]
Support for updating repository url if repo file is already exist

**Comment by acch** [comment]
There's some additional details here: https://github.com/acch/ansible-scale/issues/7

**Comment by acch** [comment]
I'm working on this now: https://github.com/acch/ibm-spectrum-scale-install-infra/tree/iss273

**Comment by acch** [comment]
I can't seem to be able to reproduce the issue described in [acch/ansible-scale#7](https://github.com/acch/ansible-scale/issues/7). Looks like `yum_repository` will now update existing files if the baseurl changes.

Ansible version: 2.9.14
Python version: 3.8.6
Managed host: RHEL 7.8

This can be verified with a quick test:
```yaml
- hosts: node1
  tasks:

    - name: test | Clean existing YUM repository
      file:
        path: /etc/yum.repos.d/spectrum-scale-gpfs.repo
        state: absent

    - command: ls -l /etc/yum.repos.d/

    - name: test | Configure new YUM repository
      yum_repository:
        name: spectrum-scale-gpfs
        description: IBM Spectrum Scale (GPFS)
        baseurl: http://infraserv/yum/gpfs/5.0.5.1/gpfs_rpms
        state: present

    - command: grep baseurl /etc/yum.repos.d/spectrum-scale-gpfs.repo

    - name: test | Modify existing YUM repository
      yum_repository:
        name: spectrum-scale-gpfs
        description: IBM Spectrum Scale (GPFS)
        baseurl: http://infraserv/yum/gpfs/5.0.5.3/gpfs_rpms
        state: present

    - command: grep baseurl /etc/yum.repos.d/spectrum-scale-gpfs.repo
```

The output of the first `grep` is:
`baseurl = http://infraserv/yum/gpfs/5.0.5.1/gpfs_rpms`

The output of the second `grep` is:
`baseurl = http://infraserv/yum/gpfs/5.0.5.3/gpfs_rpms` (version number has changed)

Hence, I guess that there were changes to the `yum_repository` module and it now works as expected (modifies existing repos).

Are you able to reproduce the issue with Ansible 2.9? If so, can you please provide more details as to what's missing?
