### ISSUE TITLE
Incorrect sequence of NFS tasks on IPv6 

### ISSUE THREAD

**Issue by rajan-mis** [IBM/ibm-spectrum-scale-install-infra#348]
```
- name: configure | Enable interface mode
  shell:
   cmd: "mmces interface mode interface --force"
  when: scale_ces_ipv6_list|length > 0
```
