### ISSUE TITLE
Development branch features implemented code check-in into master 

### ISSUE THREAD

**Issue by rajan-mis** [IBM/ibm-spectrum-scale-install-infra#40]
Development branch features implemented code check-in into master .

Development branch code ( cloud integration support, group_vars implementation code , directory based installation and defect fixes ) into master.

**Comment by rajan-mis** [comment]
Unit Test results :

**Steps:1 Define cluster hosts:**
```
[root@controllernode ibm-spectrum-scale-install-infra]# cat hosts 
# hosts:
[cluster01]
test-51 scale_cluster_quorum=true   scale_cluster_manager=true scale_cluster_gui=false
test-52 scale_cluster_quorum=true   scale_cluster_manager=true scale_cluster_gui=true
test-53 scale_cluster_quorum=true   scale_cluster_manager=true scale_cluster_gui=true
test-54 scale_cluster_quorum=true   scale_cluster_manager=true scale_cluster_gui=false
```

**Steps:2 Define NSD's and filesystem:**
```
[root@controllernode ibm-spectrum-scale-install-infra]# cat group_vars/all.yml 
---
scale_storage:
  - filesystem: gpfs02
    disks:
      - device: /dev/sdb
        servers: test-51
      - device: /dev/sdc
        servers: test-51
  - filesystem: gpfs03
    disks:
      - device: /dev/sdd
        nsd: nsd_1
        servers: test-51
```

**Steps:3 Without scale_version , user only need to define installation method.**
```
[root@controllernode ibm-spectrum-scale-install-infra]# cat playbook.yml 
---
- hosts: cluster01
  vars:
    - scale_install_localpkg_path: /home/rajan/Spectrum_Scale_Advanced-5.0.4.0-x86_64-Linux-install
  roles:
     - core/precheck
     - core/node
     - core/cluster
     - gui/precheck
     - gui/node
     - gui/cluster
     - gui/postcheck
     - zimon/precheck
     - zimon/node
     - zimon/cluster
```

**Steps:4 , Run playbook and start GPFS cluster creation**
```
[root@controllernode ibm-spectrum-scale-install-infra]# ./ansible.sh 
Running ansible-playbook -i hosts playbook.yml
```

**GPFS states:**
```
[root@test-51 ~]# mmgetstate -a

 Node number  Node name        GPFS state  
-------------------------------------------
       1      test-51                        active
       2      test-52                       active
       3      test-53                       active
       4      test-54                       active
```

**GPFS cluster information**
```
[root@test-51 ~]# mmlscluster

GPFS cluster information
========================
  GPFS cluster name:         gpfs1.local
  GPFS cluster id:           6993155638008074462
  GPFS UID domain:           gpfs1.local
  Remote shell command:      /usr/bin/ssh
  Remote file copy command:  /usr/bin/scp
  Repository type:           CCR

GPFS cluster configuration servers:
-----------------------------------
  Primary server:    test-51.localnet.com (not in use)
  Secondary server:  (none)

 Node  Daemon node name       IP address   Admin node name        Designation
------------------------------------------------------------------------------
   1   test-51.localnet.com  10.0.100.51  rajan-51.localnet.com  quorum-manager-perfmon
   2   test-52.localnet.com  10.0.100.52  rajan-52.localnet.com  quorum-manager-perfmon
   3   test-53.localnet.com  10.0.100.53  rajan-53.localnet.com  quorum-manager-perfmon
   4   test-54.localnet.com  10.0.100.54  rajan-54.localnet.com  quorum-manager-perfmon
```

**NSD and Filesystems:**
```
[root@test-51 ~]# mmlsnsd -X

 Disk name       NSD volume ID      Device          Devtype  Node name or Class       Remarks          
-------------------------------------------------------------------------------------------------------
 nsd_1           0A0064335E7DD186   /dev/sdd        generic  test-51.localnet.com    server node
 nsd_test_51_sdb 0A0064335E7DD181   /dev/sdb        generic  test-51.localnet.com    server node
 nsd_test_51_sdc 0A0064335E7DD182   /dev/sdc        generic  test-51.localnet.com    server node
```

**GUI servers:**
```
[root@test-51 ~]# mmlsnodeclass
Node Class Name       Members
--------------------- -----------------------------------------------------------
GUI_MGMT_SERVERS      test-52.localnet.com,test-53.localnet.com
GUI_SERVERS                  test-52.localnet.com,test-53.localnet.com
                                         test-54.localnet.com,test-51.localnet.com
```
