### ISSUE TITLE
Unable to set maxDataReplicas

### ISSUE THREAD

**Issue by benformosa** [IBM/ibm-spectrum-scale-install-infra#564]
**Describe the bug**
The core role fails when attempting to set `maxDataReplicas` or `maxMetadataReplicas`.

#426 set the `-M` and `-R` options in [`roles/core/cluster/tasks/storage_fs.yml`](https://github.com/IBM/ibm-spectrum-scale-install-infra/blob/d05670d868fa5635d386b531ed5eb36ccea64a21/roles/core/cluster/tasks/storage_fs.yml#L94), but not the equivalent task in [`roles/core/cluster/tasks/storage.yml`](https://github.com/IBM/ibm-spectrum-scale-install-infra/blob/d05670d868fa5635d386b531ed5eb36ccea64a21/roles/core/cluster/tasks/storage.yml#L124)

The task runs a `mmcrfs` command with options `-m` and `-r`, but not `-M` and `-R`.

`mmcrfs` fails with this message:

```
mmcrfs: DefaultMetadataReplicas must be <= MaxMetadataReplicas
mmcrfs: Command failed. Examine previous error messages to determine cause.
```

**To Reproduce**
1. Create a [`storage_vars.yml`](https://github.com/IBM/ibm-spectrum-scale-install-infra/blob/master/samples/vars/storage_vars.yml) to create a filesystem, and set `maxMetadataReplicas`, `defaultMetadataReplicas`, `maxDataReplicas`, and `defaultDataReplicas `to `3`:

```yaml
---
scale_storage:
  - filesystem: gpfs01
    maxMetadataReplicas: 3
    defaultMetadataReplicas: 3
    maxDataReplicas: 3
    defaultDataReplicas: 3
  ```

2. Run [`playbook_storage.yml`](https://github.com/IBM/ibm-spectrum-scale-install-infra/blob/master/samples/playbook_storage.yml)

**Expected behavior**
A new filesystem should be created with options `-M 3 -m 3 -R 3 -r 3`

**Environment**
RHEL 8
``` bash
$ ansible --version
ansible 2.9.24
  config file = /home/bf/code/ansible-playbook-scale-sharednothing/ansible.cfg
  configured module search path = ['/home/bf/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Mar 18 2021, 08:58:41) [GCC 8.4.1 20200928 (Red Hat 8.4.1-1)]
$ python --version
Python 3.6.8
```

**Comment by benformosa** [comment]
Tested and working using dev branch (a391be6c835ca128e7853ff1e2f3f36e3762d131). Thanks so much!

Storage vars:
```yaml
scale_storage:
  - filesystem: cesSharedRoot
    blockSize: 256K
    maxMetadataReplicas: 3
    defaultMetadataReplicas: 3
    maxDataReplicas: 3
    defaultDataReplicas: 3
    numNodes: 5
    automaticMountOption: true
    strictReplication: always
    disks:
      - device: /dev/sdc
        nsd: scalesn_3_1
        servers: scalesn-3
        failureGroup: 0
        usage: dataAndMetadata
        pool: system
      - device: /dev/sdc
        nsd: scalesn_4_1
        servers: scalesn-4
        failureGroup: 1
        usage: dataAndMetadata
        pool: system
      - device: /dev/sdc
        nsd: scalesn_5_1
        servers: scalesn-5
        failureGroup: 2
        usage: dataAndMetadata
        pool: system
```

Filesystem details:
```
$ sudo mmlsfs cesSharedRoot | grep 'data replicas'
 -m                 3                        Default number of metadata replicas
 -M                 3                        Maximum number of metadata replicas
 -r                 3                        Default number of data replicas
 -R                 3                        Maximum number of data replicas
```
