### ISSUE TITLE
"samples/playbook_gui.yml" does not exist, but mentioned in GUI

### ISSUE THREAD

**Issue by troppens** [IBM/ibm-spectrum-scale-install-infra#580]
The title says all. README.md refers to `samples/playbook_gui.ym`, but this file does not exist.

**Comment by rajan-mis** [comment]
Thanks @troppens . we will fix this.

Sample playbook for GUI:

```
---
- hosts: scale01.example.com
  vars:
    - scale_version: 5.0.4.0
    - scale_install_localpkg_path: /path/to/Spectrum_Scale_Standard-5.0.4.0-x86_64-Linux-install
  roles:
    - core/precheck
    - core/node
    - core/cluster
    - gui/precheck
    - gui/node
    - gui/cluster
```

Please set `scale_cluster_gui: true ` for required host entry.
