### ISSUE TITLE
Unable to add Scale HPT to my cluster

### ISSUE THREAD

**Issue by moonlight16** [IBM/ibm-spectrum-scale-install-infra#670]
**Describe the bug**
Installing `scale_hpt` role failed with:

```
TASK [ibm.spectrum_scale.scale_hpt/node : install | Check installation method] ****************************************************************************************************************************
fatal: [arch1-master1.sl.cloud9.ibm.com -> localhost]: FAILED! => {
    "assertion": "scale_installmethod is defined",
    "changed": false,
    "evaluated_to": false,
    "msg": "Please set the appropriate variable 'scale_install_*' for your desired installation method!"
}
```

It seems the `scale_install_remotepkg_path` support was missing.  

Once I added it to `install.yml`, next, I ran into missing `install_remote_pkg.yml` file.  I created this file with appropriate pkg installation.  

These changes worked so I'll submit these changes in a PR.

**To Reproduce**
Here's my playbook:

```
# playbook.yml:
---
- hosts: arch1
  collections:
    - ibm.spectrum_scale
  vars:
    - scale_version: 5.1.4.1
    - scale_install_remotepkg_path: /root/Spectrum_Scale_Data_Management-5.1.4.1-x86_64-Linux-install
  roles:
    - core/precheck
    - core/node
    - core/cluster
    - core/postcheck
    - scale_hpt/precheck
    - scale_hpt/node
    - scale_hpt/postcheck
    - gui/precheck
    - gui/node
    - gui/cluster
```

Here's my inventory:

```
[arch1]
arch1-master1.sl.cloud9.ibm.com ansible_user=root scale_cluster_quorum=true scale_cluster_manager=true scale_cluster_gui=true
arch1-worker1.sl.cloud9.ibm.com ansible_user=root scale_cluster_quorum=true scale_cluster_manager=true scale_cluster_gui=true
arch1-worker2.sl.cloud9.ibm.com ansible_user=root scale_cluster_quorum=true scale_cluster_manager=true scale_cluster_gui=true
```

**Expected behavior**
I expected to install HPT and find the utility `mmafmtransfer`.

**Environment**

```
❯ ansible --version
ansible [core 2.13.1]
  config file = None
  configured module search path = ['/Users/jacohn/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/6.1.0/libexec/lib/python3.10/site-packages/ansible
  ansible collection location = /Users/jacohn/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.10.5 (main, Jun 23 2022, 17:15:25) [Clang 13.1.6 (clang-1316.0.21.2.5)]
  jinja version = 3.1.2
  libyaml = True
❯ python3 --version
Python 3.10.5
# Deployment
rpm -qa | grep gpfs
```

**Screenshots**

**Additional context**
