### ISSUE TITLE
"install | Compare checksums" fails, if whitespace in path name

### ISSUE THREAD

**Issue by troppens** [IBM/ibm-spectrum-scale-install-infra#80]
Failing task:
```
TASK [spectrum_scale_core/node : install | Compare checksums] **********************************************************
fatal: [spectrumscale]: FAILED! => {"msg": "The conditional check 'scale_install_md5_sum.strip().split().0 == scale_install_localpkg.stat.md5' failed. The error was: error while evaluating conditional (scale_install_md5_sum.strip().split().0 == scale_install_localpkg.stat.md5): 'dict object' has no attribute 'md5'"}
```

Failing playbook:
```
# spectrumscale.yml
---

- hosts: spectrumscale
  vars:
    - scale_install_localpkg_path: "/mylab/software/Spectrum Scale 5.0.4.1 Developer Edition/Spectrum_Scale_Developer-5.0.4.1-x86_64-Linux-install"
install"
  roles:
    - spectrum_scale_core/precheck
    - spectrum_scale_core/node
    - spectrum_scale_core/cluster
```

The issue can be mitigated avoiding spaces in directory names.

Unfortunately the Developer Edition extracts per default to a directory with spaces in the name. Therefore it can be expected that folks that tries the Developer Edition runs into this issue.
